### ISSUE TITLE
Support for OS X 10.13?

### ISSUE THREAD

**Issue by kahays** [elalish/manifold#576]
Hello! I am not familiar with C++ but was wondering if it would be feasible to make changes for Manifold to be compatible with Mac OS X 10.13 (and possibly lower.)

I'm building with `make -k` on OS X 10.13 and the two errors below in `csg_tree.cpp` (lines 85 and 87) appear to be the only blockers to a full build:

`manifold/src/manifold/src/csg_tree.cpp:85:14: error: call to unavailable function 'get': introduced in macOS 10.14`
`     return std::get<std::shared_ptr<const Manifold::Impl>>(p).get();`
`manifold/src/manifold/src/csg_tree.cpp:87:14: error: call to unavailable function 'get': introduced in macOS 10.14`
`     return std::get<std::shared_ptr<Manifold::Impl>>(p).get();`

Naïve searching turned up a StackOverflow answer suggesting that there were [doable workarounds](https://stackoverflow.com/questions/52521388/stdvariantget-does-not-compile-with-apple-llvm-10-0) using `std::get_if` and some boilerplate error handling code, but again I'm not versed in C++ and am unsure of the real amount of work to ensure compatibility.

Thank you for your work on this library, its inclusion in OpenSCAD has made my workflow much faster and easier :)

**Comment by pca006132** [comment]
sure, this doesn't look too complicated. we don't need the error handling code because we check the variants first. replacing `std::get` with `std::get_if` should be enough.

**Comment by elalish** [comment]
Out of curiosity, what the is the need for OSX 10.13? Can we compile on 13.6 and still run the executable on 10.13?

**Comment by kahays** [comment]
Thank you folks for considering this :)

I'm attempting to compile the latest OpenSCAD for my OS X 10.13 machine, and I was told the reason that OpenSCAD support had shifted to OS X ≥10.14 was in part because Manifold required it. I'm a little lost in the weeds, but I thought a good start would be to get the standalone Manifold project to compile on 10.13 and then integrate any changes into the OpenSCAD repository.

I'd be happy to try an executable compiled on 13.6, but unfortunately I don't have access to a machine to compile it myself.

**Comment by kintel** [comment]
@elalish Just to clarify: macOS allows you to build binaries for "any" version of macOS, independently on which version of the OS, Xcode etc. you're using. You can use the `CMAKE_OSX_DEPLOYMENT_TARGET` setting in CMake for this.
